services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    env_file:
      - .env
    environment:
      - COMPOSER_PROCESS_TIMEOUT=0

  frontend:
    image: node:20
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    command: >
      sh -c "npm install && npm run build"

  composer:
    image: composer:latest
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html

volumes:
  database: